# flops = 1.0G, params = 10M top1 = 78.0  top5 = 93.7
burgerformer_tiny = {
    'stage-1': {'macro': {'depth': 2, 'width': 32, 'ratio': 4}, 'meso': {'use_layer_scale': [False, True, True], 'is_drop': [False, True, True], '1': 'skip-skip-skip-skip-skip', '2': 'skip-GN-dwise_3x3-skip-gelu', '3': 'skip-skip-avgpool-LN-silu', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-2': {'macro': {'depth': 4, 'width': 96, 'ratio': 1}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-dwise_3x3-LN-silu', '2': 'skip-LN-dwise_3x3-skip-relu6', '3': 'skip-skip-dwise_3x3-BN-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-3': {'macro': {'depth': 4, 'width': 192, 'ratio': 4}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-LN-avgpool-skip-silu', '2': 'skip-skip-skip-skip-skip', '3': 'skip-GN-spatial_mlp-skip-skip', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-4': {'macro': {'depth': 4, 'width': 384, 'ratio': 6}, 'meso': {'use_layer_scale': [False, True, False], 'is_drop': [False, True, False], '1': 'skip-skip-skip-skip-skip', '2': 'skip-skip-dwise_3x3-LN-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}
}
# flops = 2.1G, params = 14M top1 = 80.4  top5 = 95.0
burgerformer_small = {
    'stage-1': {'macro': {'depth': 3, 'width': 96, 'ratio': 1}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-GN-avgpool-skip-silu', '2': 'skip-skip-dwise_3x3-LN-silu', '3': 'skip-skip-dwise_3x3-BN-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-2': {'macro': {'depth': 3, 'width': 128, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-conv_1x1-BN-relu6', '2': 'skip-skip-dwise_3x3-GN-skip', '3': 'skip-skip-avgpool-LN-silu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-3': {'macro': {'depth': 5, 'width': 256, 'ratio': 4}, 'meso': {'use_layer_scale': [True, True, False], 'is_drop': [True, True, False], '1': 'skip-skip-dwise_3x3-BN-gelu', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}, 
    'stage-4': {'macro': {'depth': 4, 'width': 512, 'ratio': 4}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-avgpool-LN-relu6', '2': 'skip-skip-dwise_3x3-GN-skip', '3': 'skip-BN-spatial_mlp-skip-silu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}
}
# flops = 3.9G, params = 26M top1 = 82.7  top5 = 96.2
burgerformer_base = {
    'stage-1': {'macro': {'depth': 2, 'width': 96, 'ratio': 2}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-avgpool-GN-silu', '2': 'skip-skip-skip-skip-skip', '3': 'skip-LN-avgpool-skip-skip', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-2': {'macro': {'depth': 2, 'width': 128, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-BN-dwise_3x3-skip-skip', '2': 'skip-skip-skip-skip-skip', '3': 'skip-GN-dwise_3x3-skip-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-3': {'macro': {'depth': 6, 'width': 320, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-self_atten-GN-silu', '2': 'skip-skip-dwise_3x3-LN-silu', '3': 'skip-skip-conv_1x1-LN-gelu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-4': {'macro': {'depth': 3, 'width': 512, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-LN-self_atten-skip-gelu', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-avgpool-GN-silu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}
}
# flops = 6.5G, params = 36M top1 = 83.0 top5 = 96.3
burgerformer_large = {
    'stage-1': {'macro': {'depth': 4, 'width': 96, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-avgpool-LN-skip', '2': 'skip-skip-dwise_3x3-LN-silu', '3': 'skip-GN-dwise_3x3-skip-skip', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-2': {'macro': {'depth': 4, 'width': 128, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-BN-dwise_3x3-skip-silu', '2': 'skip-GN-dwise_3x3-skip-relu6', '3': 'skip-BN-conv_1x1-skip-skip', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-3': {'macro': {'depth': 8, 'width': 320, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-self_atten-GN-relu6', '2': 'skip-skip-dwise_3x3-GN-gelu', '3': 'skip-GN-conv_1x1-skip-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-4': {'macro': {'depth': 4, 'width': 512, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-BN-conv_1x1-skip-silu', '2': 'skip-skip-dwise_3x3-GN-skip', '3': 'skip-GN-self_atten-skip-gelu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}
}


min_arch = {
    'stage-1': {'macro': {'depth': 1, 'width': 32, 'ratio': 1}, 'meso': {'use_layer_scale': [False, True, False], 'is_drop': [False, True, False], '1': 'skip-skip-skip-skip-skip', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}, 
    'stage-2': {'macro': {'depth': 1, 'width': 64, 'ratio': 1}, 'meso': {'use_layer_scale': [False, True, False], 'is_drop': [False, True, False], '1': 'skip-skip-skip-skip-skip', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}, 
    'stage-3': {'macro': {'depth': 1, 'width': 128, 'ratio': 1}, 'meso': {'use_layer_scale': [False, True, False], 'is_drop': [False, True, False], '1': 'skip-skip-skip-skip-skip', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}, 
    'stage-4': {'macro': {'depth': 1, 'width': 128, 'ratio': 1}, 'meso': {'use_layer_scale': [False, True, False], 'is_drop': [False, True, False], '1': 'skip-skip-skip-skip-skip', '2': 'skip-skip-skip-skip-skip', '3': 'skip-skip-skip-skip-skip', '0->1': 'none', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'none'}}
}
max_arch = {
    'stage-1': {'macro': {'depth': 4, 'width': 96, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-dwise_3x3-BN-relu6', '2': 'skip-skip-dwise_3x3-BN-relu6', '3': 'skip-skip-dwise_3x3-BN-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-2': {'macro': {'depth': 4, 'width': 128, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-skip-dwise_3x3-BN-relu6', '2': 'skip-skip-dwise_3x3-BN-relu6', '3': 'skip-skip-dwise_3x3-BN-relu6', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-3': {'macro': {'depth': 8, 'width': 320, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-LN-self_atten-skip-gelu', '2': 'skip-skip-dwise_3x3-BN-relu6', '3': 'skip-LN-self_atten-skip-gelu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}, 
    'stage-4': {'macro': {'depth': 4, 'width': 512, 'ratio': 6}, 'meso': {'use_layer_scale': [True, True, True], 'is_drop': [True, True, True], '1': 'skip-LN-self_atten-skip-gelu', '2': 'skip-skip-dwise_3x3-BN-relu6', '3': 'skip-LN-self_atten-skip-gelu', '0->1': 'skip', '0->2': 'none', '1->2': 'skip', '0->3': 'none', '1->3': 'none', '2->3': 'skip'}}
}
